name: soundscapy-dev
channels:
- defaults
- conda-forge
dependencies:
- python=3.10
- pandas=1.4.3
- pyjanitor=0.22.0
- jupyter=1.0.0
- scipy=1.7.3
- pytest=7.1.2
- seaborn=0.11.2
- matplotlib=3.5.1
- pyyaml=6.0
- conda=4.13.0
- pip=22.1.2
- openpyxl=3.0.10
- pip:
  - scikit-maad==1.3
  - mosqito==1.0.8
  - acoustics==0.2.6
