name: soundscapy-dev
channels:
- defaults
- conda-forge
dependencies:
- python=3.7.12
- pandas>=1.2.3
- pyjanitor>=0.22.0
- jupyter>=1.0.0
- scipy>=1.7.3
- pytest>=7.1.3
- seaborn>=0.12.0
- matplotlib>=3.5.2
- pyyaml>=6.0
- conda>=22.9.0
- pip>=22.2.2
- openpyxl>=3.0.10
- numpy>=1.21.5
- pip:
  - scikit-maad==1.3
  - mosqito==1.0.8
  - acoustics==0.2.6
